### PR TITLE
[WIP] Implement ZeRO Stage 3 (FSDP)

### PR DESCRIPTION
**Pull request by jinok2im**
## Title

- Implement ZeRO Stage 3 (FullyShardedDataParallel)

## Description

- [x] Add reduce_scatter_bucketer.py
    - [x] Add test_reduce_scatter_bucketer.py
- [x] Add flatten_params_wrapper.py
    - [x] Add test_flatten_params_wrapper.py
- [x] Add containers.py
    - [x] Add test_containers.py
- [x] Add parallel.py
    - [x] Add test_parallel.py
- [x] Add fsdp_optim_utils.py
- [x] Update fsdp.py
- [x] Add auto_wrap.py
    - [x] Add test_wrap.py

### CODE REVIEW

**Comment by hyunwoongko** [comment]
@jinok2im Let's migrate this work based on the Fairscale library.

**Comment by jinok2im** [comment]
@hyunwoongko Yes, I'll continue to work based on fairscale, and I'll remove the change of existing commits of this PR.

**Comment by jinok2im** [comment]
@hyunwoongko Yes, I'll continue to work based on fairscale, and I'll remove the change of existing commits of this PR.

**Comment by hyunwoongko** [comment]
@jinok2im is there sdd offloading feature in Fairscale?

**Comment by jinok2im** [comment]
@hyunwoongko Yes, it's under experimental dir.
You can find it here. https://github.com/facebookresearch/fairscale/blob/main/fairscale/experimental/nn/ssd_offload.py

**Comment by jinok2im** [comment]
@hyunwoongko There is no way to test now. lol
Just brought it for later.

**Comment by jinok2im** [comment]
I think so. I placed it at `oslo/torch/experimental/nn/ssd_offload.py`

**Pull request closed without merging**
