### PR TITLE
[WIP] Implement TP 2D

### PR DESCRIPTION
**Pull request by hyunwoongko**

### CODE REVIEW

**Comment by hyunwoongko** [comment]
cc @bzantium @seopbo

**Comment by bzantium** [comment]
> 

Thanks for the comment! I will reflect it on next commit.

**Comment by hyunwoongko** [comment]
or you can import that functions in the `__init__(self)` method of class and you can set that functions as attributes like `self.fn = fn`. anyway, What I am saying is we don't need to import all the function at the top of the code.

**Comment by bzantium** [comment]
> @bzantium We can import that functions in the method no? I think adding that functions in `__init__.py` with importing in method is better. what do you think?

import function was originally called in forward so I moved it to the top. If it is called at __init__, it looks okay but I don't get significant difference. Is it for readability?

**Comment by hyunwoongko** [comment]
I think accessibility of the functions is more important than readability.

**Comment by bzantium** [comment]
> or you can import that functions in the `__init__(self)` method of class and you can set that functions as attributes like `self.fn = fn`. anyway, What I am saying is we don't need to import all the function at the top of the code.

I think importing functions in `forward` is better.

**Comment by bzantium** [comment]
> I think you need to compare with non-parallel version. for example, Linear2D vs nn.Linear. and their ourputs must be same.

I added comparison between parallel and non-parallel at testing. I checked all results are correct but please double check these.

**Comment by hyunwoongko** [comment]
I checked all. let's make wrapper together !

**Pull request merged**
