### PR TITLE
Implementation of Sequential Parallelism

### PR DESCRIPTION
**Pull request by ohwi**
## SP with DP implementation

- Implemented SP wrapper with DP

## Description

- `SequenceDataParallel` works like native torch DDP with SP
- you can find details in the file `oslo/tests/torch/nn/parallal/data_parallel/test_sp.py`

### CODE REVIEW

**Comment by hyunwoongko** [comment]
Could you run `pre-commit` before commit?

**Comment by ohwi** [comment]
Hi. Why pre-commit suggests changing the line below?

```for i in range(1000):
     dummy_input = torch.randint(vocab_size, (batch_size, sequence_length)).long().cuda()
-    dummy_output = torch.randint(vocab_size, (batch_size, sequence_length)).long().cuda()
+    dummy_output = (
+        torch.randint(vocab_size, (batch_size, sequence_length)).long().cuda()
+    )
```

This will make the code flow different.

**Comment by hyunwoongko** [comment]
no it's same. why different? `(something)` is not a tuple.

**Comment by ohwi** [comment]
Oh okay

**Comment by ohwi** [comment]
Finished formatting.

**Pull request merged**
